# Generated by Django 2.1.5 on 2019-09-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events_operations', '0002_auto_20190921_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('photo_id', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='attendees',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_operations.user')),
                ('event', models.ManyToManyField(to='events_operations.Event')),
            ],
            bases=('users_operations.user',),
        ),
    ]
