# Generated by Django 2.2.4 on 2019-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendees',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='attendees',
            name='entity',
            field=models.CharField(choices=[('FA', 'Facultad de Arquitectura'), ('FAD', 'Facultad de Artes y Diseno'), ('FC', 'Facultad de Ciencias'), ('FCPS', 'Facultad de Ciencias Politicas y Sociales'), ('FCA', 'Facultad de Contaduria y Administracion'), ('FD', 'Facultad de Derecho'), ('FE', 'Facultad de Economia'), ('FESAc', 'Facultad de Estudios Superiores (FES) Acatlan'), ('FESAc', 'Facultad de Estudios Superiores (FES) Acatlan'), ('FESAr', 'Facultad de Estudios Superiores (FES) Aragon'), ('FESC', 'Facultad de Estudios Superiores (FES) Cuautitlan'), ('FESI', 'Facultad de Estudios Superiores (FES) Iztacala'), ('FESZ', 'Facultad de Estudios Superiores (FES) Zaragoza'), ('FLL', 'Facultad de Filosofia y Letras'), ('FI', 'Facultad de Ingenieria'), ('FMe', 'Facultad de Medicina'), ('FMVZ', 'Facultad de Medicina Veterinaria y Zootecnia'), ('FMu', 'Facultad de Musica'), ('FO', 'Facultad de Odontologia'), ('FP', 'Facultad de Psicologia'), ('FQ', 'Facultad de Quimica')], default='FC', max_length=10),
        ),
    ]
