# Generated by Django 2.1.5 on 2019-09-27 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_operations', '0002_auto_20190926_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_operations.User'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_operations.User'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_operations.User'),
        ),
    ]
