# Generated by Django 2.2.4 on 2019-10-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=10)),
                ('attendees_list', models.ManyToManyField(to='users_operations.Attendees')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_operations.Organizer')),
                ('staff_list', models.ManyToManyField(to='users_operations.Staff_event')),
                ('tag', models.ManyToManyField(to='events_operations.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(default='', max_length=20)),
                ('confirm', models.BooleanField(default=False)),
                ('invitation', models.BooleanField()),
                ('event', models.ManyToManyField(to='events_operations.Event')),
                ('user', models.ManyToManyField(to='users_operations.Attendees')),
            ],
        ),
    ]
