# Generated by Django 2.1.5 on 2019-09-14 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('organizer', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('eventCover', models.ImageField(upload_to='tmp')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('idOrganizer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('idEmployee', models.ManyToManyField(to='events_operations.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('idTag', models.ManyToManyField(to='events_operations.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='idEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_operations.Organizer'),
        ),
        migrations.AddField(
            model_name='category',
            name='idCategory',
            field=models.ManyToManyField(to='events_operations.Event'),
        ),
    ]
