# Generated by Django 2.1.5 on 2019-09-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='idCategory',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='idEmployee',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='idTag',
            new_name='event',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
