# Generated by Django 2.1.5 on 2019-10-23 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees_list',
            field=models.ManyToManyField(blank=True, to='users_operations.Attendees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff_list',
            field=models.ManyToManyField(blank=True, to='users_operations.Staff_event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(blank=True, to='events_operations.Tag'),
        ),
    ]
