# Generated by Django 2.2.4 on 2019-12-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_operations', '0002_auto_20191023_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='qr_code',
            field=models.ImageField(upload_to=''),
        ),
    ]
