# Generated by Django 2.1.5 on 2019-09-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_operations', '0003_auto_20190926_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees_list',
            field=models.ManyToManyField(to='users_operations.Attendees'),
        ),
    ]
