# Generated by Django 2.2.4 on 2019-12-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_operations', '0003_auto_20191201_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees_list',
        ),
    ]
