# Generated by Django 2.1.5 on 2019-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_operations', '0004_auto_20190927_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees_list',
            field=models.ManyToManyField(to='users_operations.Attendees'),
        ),
    ]
