# Generated by Django 2.2.4 on 2019-10-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_operations', '0006_auto_20191001_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees_list',
            field=models.ManyToManyField(to='users_operations.Attendees'),
        ),
    ]
