# Generated by Django 2.2.4 on 2019-10-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_operations', '0007_auto_20191013_1823'),
        ('events_operations', '0007_auto_20191013_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees_list',
            field=models.ManyToManyField(to='users_operations.Attendees'),
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(default='', max_length=20)),
                ('confirm', models.BooleanField(default=False)),
                ('invitation', models.BooleanField()),
                ('event', models.ManyToManyField(to='events_operations.Event')),
                ('user', models.ManyToManyField(to='users_operations.Attendees')),
            ],
        ),
    ]
