# Generated by Django 2.2.4 on 2019-10-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_operations', '0009_auto_20191013_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='user',
            field=models.ManyToManyField(to='users_operations.Attendees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees_list',
            field=models.ManyToManyField(to='users_operations.Attendees'),
        ),
    ]
